Projeto/Despensometro2/Despensometro2/Models/produto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Despensometro2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public produto()
        {
            this.ingrediente = new HashSet<ingrediente>();
            this.listaCompras_produto = new HashSet<listaCompras_produto>();
            this.produto_estoque = new HashSet<produto_estoque>();
            this.receitaInternet = new HashSet<receitaInternet>();
        }
    
        public int produto_id { get; set; }
        public int fabricante_id { get; set; }
        public Nullable<int> tipo_id { get; set; }
        public string produto_nome { get; set; }
        public string produto_peso { get; set; }
        public string sabor { get; set; }
        public string numero_ean { get; set; }
    
        public virtual fabricante fabricante { get; set; }
        public virtual ICollection<ingrediente> ingrediente { get; set; }
        public virtual ICollection<listaCompras_produto> listaCompras_produto { get; set; }
        public virtual tipo tipo { get; set; }
        public virtual ICollection<produto_estoque> produto_estoque { get; set; }
        public virtual ICollection<receitaInternet> receitaInternet { get; set; }
    }
}

Projeto/Despensometro2/Despensometro2/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Despensometro2.Repositories;
using Despensometro2.Models;


namespace Despensometro2.Controllers
{
    public class ProdutoController : Controller
    {
        private Repository<produto> repository;

        public ProdutoController(){
            repository = new Repository<produto>();    
        }

        public ActionResult Index()
        {
            List<produto> list = repository.ListAll().OrderBy(p => p.produto_nome).ToList();

            return View("~/Views/Produto/Produto.cshtml", list);
        }

        public JsonResult PesquisaProduto(string valor)
        {
            ProdutoRepository listaProdutos = new ProdutoRepository();

            var lista = listaProdutos.FiltraProduto(valor);

            return Json(lista, JsonRequestBehavior.AllowGet);
        }

       
        [HttpGet]
        public ActionResult AdicionarProduto()
        {
            Repository<tipo> repTipo = new Repository<tipo>();

            ViewBag.categorias = repTipo.ListAll();

            return View();
        }

        [HttpPost]
        public JsonResult AdicionarProduto(ProdutoSimplificado objeto)
        {
            bool resposta = false;

            if (objeto.produto_nome != null && objeto.produto_categoria != null && objeto.produto_fabricante != null)
            {
                Repository<tipo> repTipo = new Repository<tipo>();

                tipo tipoProd = null;

                foreach (var t in repTipo.ListAll())
                {
                    if (t.categoria_produto.Equals(objeto.produto_categoria.Replace(" ", "")))
                    {
                        tipoProd = t;
                        break;
                    }
                }

                produto p = new produto();

                p.produto_nome = objeto.produto_nome;
                p.produto_peso = objeto.produto_peso;
                p.sabor = objeto.sabor;
                p.tipo_id = tipoProd.tipo_id;
                p.numero_ean = objeto.numero_ean;
                p.fabricante = new fabricante() { nome_fabricante = objeto.produto_fabricante };

                repository.AddElement(p);

                resposta = true;
            }
            else
            {
                resposta = false;
            }

            

            return Json(resposta, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditarProduto(int id)
        {
            produto p = repository.GetById(id);
            Repository<tipo> repTipo = new Repository<tipo>();
            List<SelectListItem> types = new List<SelectListItem>();

            types.Add(new SelectListItem() { Value = p.tipo.tipo_id.ToString(), Text = p.tipo.categoria_produto });

            foreach (tipo t in repTipo.ListAll().OrderBy(obj => obj.categoria_produto))
            {
               if(t.categoria_produto != p.tipo.categoria_produto)
                {
                    types.Add(new SelectListItem() { Value = t.tipo_id.ToString(), Text = t.categoria_produto});
                }
                
            }

            ViewBag.categorias = types;

            return View("~/Views/Produto/EditarProduto.cshtml", p);
            
        }

        [HttpPost]
        public ActionResult EditarProduto(produto objeto)
        {
            var result = false;
            
            if (objeto.produto_nome != null && objeto.tipo_id != null && objeto.fabricante.nome_fabricante != null)
            {
                repository.UpdateElement(objeto);
                ViewBag.resposta = true;
                result = true;
            }
            else
            {
                ViewBag.resposta = false;
                result = false;
            }

            produto p = repository.GetById(objeto.produto_id);
            Repository<tipo> repTipo = new Repository<tipo>();
            List<SelectListItem> types = new List<SelectListItem>();

            foreach (tipo t in repTipo.ListAll().OrderBy(obj => obj.categoria_produto))
            {
                types.Add(new SelectListItem() { Value = t.tipo_id.ToString(), Text = t.categoria_produto });

            }

            ViewBag.categorias = types;

            var resultado = new { Success = result};

            return View(); /* Json(resultado, JsonRequestBehavior.AllowGet);*/

        }

        public ActionResult ConfirmaDeletar(int id)
        {
            produto produto =  repository.GetById(id);

            return View();
        }

        public ActionResult DeletarProduto(int id)
        {
            Boolean sucesso = repository.Delete(id);

            if (sucesso)
            {
                return View();
            }
            else
            {
                //TODO
                return View();
            }
            
        }
    }
}

Projeto/Despensometro2/Despensometro2/Views/Produto/AdicionarProduto.cshtml
@model Despensometro2.Models.produto

@{
    ViewBag.Title = "Adicionar Produto";
}

@{ 
    var categorias = ViewBag.categorias;
}

<div class="parallax-container" style="height:200px;">
    <div class="section no-pad-bot center">
        <h2 class="teal-text">Adicionar Produtos</h2>
    </div>
    <div class="parallax">
        <img src="~/Imagens/looking_labels.jpg" style="display:block; transform:translate3d(-50%, 603px, 0px)">
    </div>
</div>
<div class="section white">
    <div class="card-panel z-depth-3" style="padding: 0px">
    </div>
    <div class="row">
        <div class="col s12">
            <div class="container">
                <div class="row">

                        <div class="card hoverable white">
                            <div class="card-content">
                                <span class="card-title teal-text form">Novo Produto</span>
                                <div class="row">
                                        <div class="input-field col s12 l6 m6">
                                            <input placeholder="Ex.: Leite Ninho" id="produto_nome" type="text">
                                            <label for="produto_nome">Nome do Produto</label>
                                        </div>
                                        <div class="input-field col s12 l6 m6">
                                            <input placeholder="Ex.: Nestlé" id="produto_fabricante" type="text">
                                            <label for="produto_fabricante">Nome do Fabricante</label>
                                        </div>
                                    </div>
                                <div class="row">
                                    <div class="input-field col s12 l6 m6">
                                        <select id="select">
                                            <option value="" disabled selected>Escolha uma categoria</option>
                                            @{ var cont = 0; }
                                            @foreach (var categoria in categorias)
                                            {
                                                <option value="cont">@categoria.categoria_produto</option>
                                                cont++;
                                            }
                                            
                                        </select>
                                        <label>Categoria</label>
                                    </div>
                                    <div class="input-field col s12 l6 m6">
                                        <input placeholder="Ex.: Limão" id="produto_sabor" type="text">
                                        <label for="produto_sabor">Sabor</label>
                                    </div>
                                </div>
                                <div class="row">
                                        <div class="input-field col s12 l6 m6">
                                            <input placeholder="Ex.: 50g" id="produto_peso" type="text" class="validate">
                                            <label for="produto_peso">Peso</label>
                                        </div>
                                    <div class="input-field col s12 l6 m6">
                                        <input placeholder="Ex.: 7891000066201" id="produto_ean" type="text">
                                        <label for="produto_ean">Número do Código de Barras</label>
                                    </div>
                                </div>
                            </div>
                            <div class="card-action">
                                <div class="row">
                                    <div class="col s12">
                                        <div class="col s6 m6 l9">
                                            <a href="/Produto/Index" class="btn waves-effect waves-light right hide-on-small-and-down red lighten-1" name="action" style="color:#fff">
                                                Cancelar
                                                <i class="material-icons right">cancel</i>
                                            </a>
                                            <a href="/Produto/Index" class="btn-floating btn-large waves-effect waves-light red lighten-1 hide-on-med-and-up right">
                                                <i class="material-icons">cancel</i>
                                            </a>
                                        </div>
                                        <div class="col s6 m6 l3">
                                            <button class="btn waves-effect waves-light left hide-on-small-and-down" type="submit" onclick="submit()" name="action">
                                                Enviar
                                                <i class="material-icons right">send</i>
                                            </button>
                                            <button class="btn-floating btn-large waves-effect waves-light teal lighten-1 hide-on-med-and-up left">
                                                <i class="material-icons">send</i>
                                            </button>
                                        </div>

                                    </div>
                                    </div>
                                </div>
                            </div>
                            </div>  
                        </div>
                </div>
            </div>
        </div>
<script>
    $(document).ready(function () {
        $('.parallax').parallax();
    });
    $(document).ready(function () {
        $('select').material_select();
    });

    function submit() {
        var objeto = {
            produto_nome : $('#produto_nome').val(),
            produto_fabricante: $('#produto_fabricante').val(),
            produto_categoria: $('#select option:selected').text(),
            produto_peso: $('#produto_peso').val(),
            sabor: $('#produto_sabor').val(),
            numero_ean : $("#produto_ean").val()         
        };

        $.ajax({
            type: "POST",
            url: '/Produto/AdicionarProduto',
            datatype: 'json',
            data: objeto,
            success: function (data) {
                if (data) {
                    $(':input').val("");

                    $('#select').removeAttr('selected').val('').attr('selected', true);;

                    Materialize.toast("Novo produto cadastrado com sucesso :)", 5000);
                } else {
                    Materialize.toast("O produto não pode ser cadastrado :(", 5000);
                }
            }
        });
    }
   
</script>

Projeto/Despensometro2/Despensometro2/Views/Produto/EditarProduto.cshtml
@model Despensometro2.Models.produto

@{
    ViewBag.Title = "Editar Produto";
}

@{
    var categorias = ViewBag.categorias;
}

<div class="parallax-container" style="height:200px;">
    <div class="section no-pad-bot center">
        <h2 class="teal-text">Editar Produtos</h2>
    </div>
    <div class="parallax">
        <img src="~/Imagens/looking_labels.jpg" style="display:block; transform:translate3d(-50%, 603px, 0px)">
    </div>
</div>
<div class="section white">
    <div class="card-panel z-depth-3" style="padding: 0px">
    </div>
    <div class="row">
        <div class="col s12">
            <div class="container">
                <div class="row">
                    @{ var obj = Model.produto_nome;
                    }
    @using (Html.BeginForm("EditarProduto", "Produto", FormMethod.Post))
    {
                    <div class="card hoverable white">
                        <div class="card-content">
                            <span class="card-title teal-text form">Editar Produto</span>
                            
                            <div class="row">
                                @Html.HiddenFor(model => Model.produto_id)
                                <div class="input-field col s12 l6 m6">
                                    @Html.EditorFor(model => Model.produto_nome)
                                    @Html.LabelFor(model => Model.produto_nome, "Nome do Produto")
                                </div>
                                <div class="input-field col s12 l6 m6">
                                    @Html.EditorFor(model => Model.fabricante.nome_fabricante)
                                    @Html.LabelFor(model => Model.fabricante.nome_fabricante, "Nome do Fabricante")
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12 l6 m6">
                                   @Html.DropDownListFor(m => m.tipo_id, (IEnumerable<SelectListItem>)ViewBag.categorias)
                                    <label>Categoria</label>
                                </div>
                                <div class="input-field col s12 l6 m6">
                                    @Html.EditorFor(model => Model.sabor)
                                    @Html.LabelFor(model => Model.sabor, "Sabor")
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12 l6 m6">
                                    @Html.EditorFor(model => Model.produto_peso)
                                    @Html.LabelFor(model => Model.produto_peso, "Peso")
                                </div>
                                <div class="input-field col s12 l6 m6">
                                    @Html.EditorFor(model => Model.numero_ean)
                                    @Html.LabelFor(model => Model.numero_ean, "Número do Código de Barras")
                                </div>
                            </div>
                        </div>
                        <div class="card-action">
                            <div class="row">
                                <div class="col s12">
                                    <div class="col s6 m6 l9">
                                        <a href="/Produto/Index" class="btn waves-effect waves-light right hide-on-small-and-down red lighten-1" name="action" style="color:#fff">
                                            Cancelar
                                            <i class="material-icons right">cancel</i>
                                        </a>
                                        <a href="/Produto/Index" class="btn-floating btn-large waves-effect waves-light red lighten-1 hide-on-med-and-up right">
                                            <i class="material-icons">cancel</i>
                                        </a>
                                    </div>
                                    <div class="col s6 m6 l3">
                                        <button class="btn waves-effect waves-light left hide-on-small-and-down" type="submit" name="action">
                                            Salvar
                                            <i class="material-icons right">check</i>
                                        </button>
                                        <button class="btn-floating btn-large waves-effect waves-light teal lighten-1 hide-on-med-and-up left"  type="submit">
                                            <i class="material-icons">check</i>
                                        </button>
                                    </div>

                                </div>
                            </div>
                        </div>
                                         
                    </div> 
                                            }
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('.parallax').parallax();
    });
    $(document).ready(function () {
        $('select').material_select();
    });

    function resposta() {

        @if(ViewBag.resposta == true){

            @:Materialize.toast("Produto atualizado com sucesso :)", 5000);
        } else if(ViewBag.resposta == false) {
            @:Materialize.toast("O produto não pode ser atualizado :(", 5000);
        }
    }

    //$(document).ready(
    //    $.getJSON("/Produto/EditarProduto", null, function (data) {               
    //        if (data == true) {
    //            Materialize.toast("Produto atualizado com sucesso :)", 5000);
    //        } else {
    //            Materialize.toast("O produto não pode ser atualizado :(", 5000);
    //        }
    //    }
    //));
    

</script>

Projeto/Despensometro2/Despensometro2/Views/Produto/Produto.cshtml
@model List<Despensometro2.Models.produto>

    @{ViewBag.Title = "Produto";}
    @Scripts.Render("~/bundles/filtra")
  

    <div class="parallax-container" style="height:200px;">
        <div class="section no-pad-bot center">
            <h1 class="teal-text">Produtos </h1>
        </div>
        <div class="parallax">
            <img src="~/Imagens/looking_labels.jpg" style="display:block; transform:translate3d(-50%, 603px, 0px)">
         </div>
    </div>
    <div class="section white">
        <div class="row z-depth-3" id="search" style="padding: 0px;">
            <div class="row">
                <div class="col s12">
                    <div class="col s12 m6 l6 offset-l3 offset-m3">
                        <div class="input-field">
                            <i class="material-icons prefix">search</i>
                            <input id="icon_prefix" onkeyup="filtra()" type="text" class="tooltipped" data-position="top" data-delay="50" data-tooltip="Procure por produtos">
                            <label for="icon_prefix">Produto</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-panel center-align">
            <a href="/Produto/AdicionarProduto" class="waves-effect waves-light btn tooltipped" data-position="top" data-delay="50" data-tooltip="Adicione um novo produto"><i class="material-icons left">add</i>Adicionar Produto</a>
        </div>
            <div class="row">
                <div class="container">
                    <table class="striped responsive-table z-depth-5 centered">
                        <thead>
                            <tr>
                                <th data-field="nome">Produto<i class="material-icons left-align">arrow_drop_down</i></th>
                                <th data-field="peso">Peso</th>
                                <th data-field="sabor">Sabor</th>
                                <th data-field="fabricante">Fabricante<i class="material-icons left-align">arrow_drop_down</i></th>
                                <th data-field="ean">Código de Barras</th>
                                <th data-field="tipo">Categoria</th>
                                <th data-field="perecibilidade">Perecível?</th>
                            </tr>
                        </thead>

                        <tbody>

                            @foreach (var p in Model)
                            {
                                <tr>
                                    <td>
                                        @if (p.produto_nome == null)
                                        {
                                            <p> - </p>
                                        }
                                        else
                                        {
                                            @Html.DisplayFor(x => p.produto_nome)
                                        }

                                    </td>
                                    <td>
                                        @if (p.produto_peso == null)
                                        {
                                            <p> - </p>
                                        }
                                        else
                                        {
                                            @Html.DisplayFor(x => p.produto_peso)
                                        }
                                    </td>
                                    <td>
                                        @if (p.sabor == null)
                                        {
                                            <p> - </p>
                                        }
                                        else
                                        {
                                            @Html.DisplayFor(x => p.sabor)
                                        }

                                    </td>
                                    <td>
                                        @if (p.fabricante.nome_fabricante == null)
                                        {
                                            <p> - </p>
                                        }
                                        else
                                        {
                                            @Html.DisplayFor(x => p.fabricante.nome_fabricante)
                                        }

                                    </td>
                                    <td>
                                        @if (p.numero_ean == null)
                                        {
                                            <p> - </p>
                                        }
                                        else
                                        {
                                            @Html.DisplayFor(x => p.numero_ean)
                                        }

                                    </td>
                                    <td>
                                        @if (p.tipo == null || p.tipo.categoria_produto == null)
                                        {
                                            <p> - </p>
                                        }
                                        else
                                        {
                                            @Html.DisplayFor(x => p.tipo.categoria_produto)
                                        }
                                    </td>
                                    <td>
                                        @if (p.tipo == null)
                                        {
                                            <p> - </p>
                                        }
                                        else
                                        {
                                            if (p.tipo.perecivel == true)
                                            {
                                                <p> Sim </p>
                                            }
                                            else
                                            {
                                                <p> Não </p>
                                            }
                                        }

                                    </td>
                                    <td>
                                        <a class="btn-floating red"><i class="material-icons tooltipped" data-position="top" data-delay="50" data-tooltip="Adicione produtos ao estoque">shopping_basket</i></a>
                                    </td>
                                    <td>
                                        <a href="/Produto/EditarProduto/@p.produto_id" class="btn-floating blue lighten-1 darken-1"><i class="material-icons tooltipped" data-position="top" data-delay="50" data-tooltip="Edite produto">mode_edit</i></a>
                                    </td>
                                    <td>
                                        <a class="btn-floating"><i class="material-icons tooltipped" data-position="top" data-delay="50" data-tooltip="Delete produto">delete</i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col s12 m8 l8 offset-l3 offset-m2">
                            <ul class="pagination">
                                <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
                                <li class="active"><a href="#!">1</a></li>
                                <li class="waves-effect"><a href="#!">2</a></li>
                                <li class="waves-effect"><a href="#!">3</a></li>
                                <li class="waves-effect"><a href="#!">4</a></li>
                                <li class="waves-effect"><a href="#!">5</a></li>
                                <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
                            </ul>
                        </div>
                        
                    </div>

                </div>

            </div>
        </div>
    <script>
        $(document).ready(function () {
            $('.parallax').parallax();
        });
        
        $(document).ready(function () {
            var elementPosition = $('#search').offset();

            $(window).scroll(function () {
                if ($(window).scrollTop() > elementPosition.top) {
                    $('#search').css('position', 'fixed').css('top', '0');
                    $('#search').css('z-index', '5').css('width', '100%').css('background-color', '#FFF');
                } else {
                    $('#search').css('position', 'relative');
                }
            });
        });
        
    </script>